export const colors = ["Black", "Brown", "Silver", "White", "Blue"];
export const orderStatus = ["Not Processed", "Processing", "Dispatched", "Cancelled", "Completed"];
export const areas = [
  "Hoàng Mai",
  "Long Biên",
  "Thanh Xuân",
  "Bắc Từ Liêm",
  "Ba Đình",
  "Cầu Giấy",
  "Đống Đa",
  "Hai Bà Trưng",
  "Hoàn Kiếm",
  "Tây Hồ",
  "Nam Từ Liêm",
  "Đan Phượng",
  "Gia Lâm",
  "Đông Anh",
  "Chương Mỹ",
  "Hoài Đức",
  "Ba Vì",
  "Mỹ Đức",
  "Phúc Thọ",
  "Thạch Thất",
  "Quốc Oai",
  "Thanh Trì",
  "Thường Tín",
  "Thanh Oai",
  "Phú Xuyên",
  "Mê Linh",
  "Sóc Sơn",
  "Ứng Hòa",
  "Sơn Tây",
];
